### PR TITLE
cargo: widen nix dependency range

### PR DESCRIPTION
**Pull request by cbgbt**
Based on the changelog for nix, it does not seem that there are relevant changes.

Happy to perform any additional testing that's needed here though!

### CODE REVIEW

**Comment by cbgbt** [comment]
Ah, looks like there are problems with the MSRV, I hadn't thought of that. I think this means this is stuck unless `gptman` also bumps its MSRV.

**Comment by cecton** [comment]
Hello :wave: 

I'd rather keep the MSRV whenever possible.... but on the other hand it's a bit annoying that we are pulling unnecessary dependencies for people who use the latest stable.

@bgilbert any thought on this?

**Comment by cecton** [comment]
I will close this for now because I don't think bumping the MSRV for the lib part of the crate is desirable and I don't see any solution at the moment.

**BUT** feel free to re-open if this is a blocking issue for you.

**Comment by Stargateur** [comment]
If you wish to increase MSRV, there is still no official policy about it, however I advice https://github.com/rust-lang/regex#minimum-rust-version-policy:

> The current tentative policy is that the minimum Rust version required to use this crate can be increased in minor version updates. For example, if regex 1.0 requires Rust 1.20.0, then regex 1.0.z for all values of z will also require Rust 1.20.0 or newer. However, regex 1.y for y > 0 may require a newer minimum version of Rust.

**Pull request closed without merging**
