### PR TITLE
Allow a wider version range for nix.

### PR DESCRIPTION
**Pull request by smalis-msft**
0.26 seems to work just fine.

### CODE REVIEW

**Comment by smalis-msft** [comment]
I think the CI is broken? Its putting out cargo errors that have nothing to do with this change.

**Comment by cecton** [comment]
Yes there is an issue at the moment which I have no idea how to fix to be honest. I guess I will have to release with the CI broken for now...

Related to #112
Related to #115

cc @yozhgoor

**Comment by yozhgoor** [comment]
Yeah sorry, didn't had much time to look into that recently

**Comment by cecton** [comment]
@yozhgoor I'll take it from you. I think I gave you something a bit too involved. I will mention you when I made a fix so you can see how I did

**Comment by cecton** [comment]
Thank you for your contribution!

**Pull request merged**
