### PR TITLE
Turn off nix's default features.

### PR DESCRIPTION
**Pull request by smalis-msft**
As far as I can tell from a quick search, this crate only uses a small subset of nix's functionality. No need to build all of it.

### CODE REVIEW

**Comment by daprilik** [comment]
Semi-related to #122, as ideally, the dep could be entirely optional

**Comment by cecton** [comment]
Awesome thanks! @smalis-msft may I ask you to make the nix dependency optional? It should be just a `#[cfg(feature = "nix")]` to add somewhere and mark the dependency as optional. Should be really easy if you don't mind :pray:

**Comment by daprilik** [comment]
Note that unless you want to release a breaking change, you'll want to add a new `default` features array (that folks can then opt-out of via `default-features = false`.

**Comment by daprilik** [comment]
@cecton Any chance you could publish a release to crates.io with these changes?

**Comment by cecton** [comment]
Hello! Yes sorry I completely forgot

**Comment by cecton** [comment]
Released 1.0.2

**Comment by daprilik** [comment]
All good, thanks again!

**Pull request merged**
